version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "18080:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    restart: unless-stopped
